#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    GYRO,           sensorGyro)
#pragma config(Sensor, dgtl1,  ENCODER_LEFT,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  ENCODER_RIGHT,  sensorQuadEncoder)
#pragma config(Motor,  port1,           lift,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightShooter,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftShooter,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           wheelFL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           wheelFR,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           wheelBR,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           wheelBL,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           conveyorRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           conveyorLeft,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          reaper,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float desiredSpeed = 9.8;

#include "SetShooterSpeedAutonomous.c";


task main()
{
	bool shooterOn = true;
	int conveyorSpeed = 100;
	int reaperSpeed = 0;

	bool slowDownPressed = false;
	bool speedUpPressed = false;
	bool shooterPressed = false;
	bool conveyorPressed = false;
	bool conveyorReversePressed = false;
	bool reaperPressed = false;
	bool reaperReversePressed = false;

	//motor[rightShooter] = 70;
	//motor[leftShooter] = 70;
	setShooterSpeed();

	while(true)
	{
		//LCD STUFF START
		bLCDBacklight = true;
		clearLCDLine(1);
		sprintf(string2, "Left: %4f", realLeftSpeed);
		displayLCDString(1,0,string2);
		clearLCDLine(0);
		sprintf(string1, "Right: %4f", realRightSpeed);
		displayLCDString(0,0,string1);
		//LCD STUFF END

		//SHOOTER STUFF START
		if (vexRT[Btn6UXmtr2] && speedUpPressed == false && desiredSpeed + .1 <= 11.5)
		{
			speedUpPressed = true;
			desiredSpeed += .2;
		}
		if (vexRT[Btn5UXmtr2] && slowDownPressed == false && desiredSpeed - .1 >= 4)
		{
			slowDownPressed = true;
			desiredSpeed -= .2;
		}
		if (vexRT[Btn7DXmtr2] && shooterPressed == false)
		{
			if(shooterOn)
			{
				shooterOn = false;
			}
			else
			{
				shooterOn = true;
			}
			shooterPressed = true;
		}
		if (!vexRT[Btn7DXmtr2])
		{
			shooterPressed = false;
		}
		if (!vexRT[Btn6UXmtr2])
		{
			speedUpPressed = false;
		}
		if (!vexRT[Btn5UXmtr2])
		{
			slowDownPressed = false;
		}
		if (!vexRT[Btn7DXmtr2])
		{
			shooterPressed = false;
		}
		//SHOOTER STUFF END

		//WHEEL STUFF START
		if (!vexRT[Btn6U] && !vexRT[Btn5U])
		{
			motor[wheelFR] = vexRT[Ch2];
			motor[wheelBR] = vexRT[Ch2];
			motor[wheelFL] = vexRT[Ch3];
			motor[wheelBL] = vexRT[Ch3];
		}
		if (vexRT[Btn6U])
		{
			motor[wheelFL] = -127;
			motor[wheelFR] = 127;
			motor[wheelBR] = -127;
			motor[wheelBL] = 127;
		}
		if (vexRT[Btn5U])
		{
			motor[wheelFL] = 127;
			motor[wheelFR] = -127;
			motor[wheelBR] = 127;
			motor[wheelBL] = -127;
		}
		//WHEEL STUFF END

		//CONVEYOR STUFF START
		motor[conveyorRight] = conveyorSpeed;
		motor[conveyorLeft] = -conveyorSpeed;
		if (vexRT[Btn8UXmtr2] && conveyorPressed == false)
		{
			conveyorPressed = true;
			if (conveyorSpeed != 0)
			{
				conveyorSpeed = 0;
			}
			else
			{
				conveyorSpeed = 100;
			}
		}
		if (vexRT[Btn8DXmtr2] && conveyorReversePressed == false)
		{
			conveyorReversePressed = true;
			if (conveyorSpeed == 100 || conveyorSpeed == 0)
			{
				conveyorSpeed = -100;
			}
			else
			{
				conveyorSpeed = 100;
			}
		}
		if (!vexRT[Btn8UXmtr2])
		{
			conveyorPressed = false;
		}
		if (!vexRT[Btn8DXmtr2])
		{
			conveyorReversePressed = false;
		}
		//CONVEYOR STUFF END

		//REAPER STUFF START
		motor[reaper] = reaperSpeed;
		if (vexRT[Btn8RXmtr2] && reaperPressed == false)
		{
			reaperPressed = true;
			if (reaperSpeed != 0)
			{
				reaperSpeed = 0;
			}
			else
			{
				reaperSpeed = 100;
			}
		}
		if (vexRT[Btn8LXmtr2] && reaperReversePressed == false)
		{
			reaperReversePressed = true;
			if (reaperSpeed == 100 || reaperSpeed == 0)
			{
				reaperSpeed = -100;
			}
			else
			{
				reaperSpeed = 100;
			}
		}
		if (!vexRT[Btn8RXmtr2])
		{
			reaperPressed = false;
		}
		if (!vexRT[Btn8LXmtr2])
		{
			reaperReversePressed = false;
		}
		//REAPER STUFF END
	}


}
